version: "3.8"
services:
  # ----------------------------------------------------------------------------
  # Setup the local redis server.
  #
  redis:
    image: redis:6-alpine
    container_name: pomodoro_redis_service
    hostname: redis
    command: [
      "redis-server",
      "--appendonly",
      "yes",
      "--requirepass",
      "${REDIS_PASS}",
      "--save",
      "60",
      "1",
      "--loglevel",
      "warning"
    ]
    ports:
      - "6379:6379"
    volumes:
      - 'pomodoro_redis_data:/data'
    networks:
      pomodoro_storage:
        aliases:
        - redis

  # ----------------------------------------------------------------------------
  # Setup the local postgres server.
  #
  postgres:
    image: postgres:13
    command: postgres -c 'max_connections=10000'
    container_name: pomodoro_postgres_service
    hostname: postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - 'pomodoro_pg_data:/var/lib/postgresql/data'
    networks:
      pomodoro_storage:
        aliases:
        - postgres

  # ----------------------------------------------------------------------------
  # Setup the local postgres server.
  #
  pgadmin:
    container_name: pomodoro_pgadmin_service
    image: dpage/pgadmin4
    environment:
        - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
        - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
        - 5050:80
    volumes:
      - 'pomodoro_pgadmin_data:/var/lib/pgadmin'
    networks:
      pomodoro_storage:
        aliases:
        - pgadmin

networks:
  pomodoro_storage:
  pomodoro_admin:
volumes:
  pomodoro_redis_data:
  pomodoro_pg_data:
  pomodoro_pgadmin_data:
